const mongoose = require('mongoose');

const couponSchema = new mongoose.Schema({
  therapistId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Therapist ID is required']
  },
  code: {
    type: String,
    required: [true, 'Coupon code is required'],
    unique: true,
    trim: true,
    uppercase: true,
    minlength: [3, 'Coupon code must be at least 3 characters'],
    maxlength: [20, 'Coupon code cannot exceed 20 characters'],
    match: [/^[A-Z0-9]+$/, 'Coupon code can only contain uppercase letters and numbers']
  },
  description: {
    type: String,
    required: [true, 'Description is required'],
    trim: true,
    maxlength: [500, 'Description cannot exceed 500 characters']
  },
  discountType: {
    type: String,
    enum: ['percentage', 'fixed'],
    required: [true, 'Discount type is required']
  },
  discountValue: {
    type: Number,
    required: [true, 'Discount value is required'],
    min: [0, 'Discount value cannot be negative'],
    validate: {
      validator: function(value) {
        if (this.discountType === 'percentage') {
          return value >= 0 && value <= 100;
        }
        return value >= 0;
      },
      message: 'Percentage discount must be between 0 and 100'
    }
  },
  minAmount: {
    type: Number,
    default: 0,
    min: [0, 'Minimum amount cannot be negative']
  },
  maxUses: {
    type: Number,
    default: null,
    min: [1, 'Maximum uses must be at least 1']
  },
  usedCount: {
    type: Number,
    default: 0,
    min: [0, 'Used count cannot be negative']
  },
  validFrom: {
    type: Date,
    required: [true, 'Valid from date is required'],
    default: Date.now
  },
  validUntil: {
    type: Date,
    required: [true, 'Valid until date is required'],
    validate: {
      validator: function(value) {
        return value > this.validFrom;
      },
      message: 'Valid until date must be after valid from date'
    }
  },
  isActive: {
    type: Boolean,
    default: true
  },
  applicableServices: [{
    type: String,
    enum: ['individual_session', 'couple_session', 'family_session', 'group_session', 'consultation', 'package', 'all'],
    required: true
  }],
  // Extended coupon features
  couponType: {
    type: String,
    enum: ['standard', 'first_time', 'referral', 'loyalty', 'seasonal', 'emergency'],
    default: 'standard'
  },
  targetAudience: {
    type: String,
    enum: ['all', 'new_clients', 'existing_clients', 'referred_clients', 'premium_clients'],
    default: 'all'
  },
  // Usage restrictions
  restrictions: {
    oneTimePerClient: {
      type: Boolean,
      default: true
    },
    requiresMinimumSessions: {
      type: Number,
      default: 0,
      min: 0
    },
    excludedDates: [{
      type: Date
    }],
    dayOfWeekRestrictions: [{
      type: String,
      enum: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
    }],
    timeRestrictions: {
      startTime: String, // HH:MM format
      endTime: String    // HH:MM format
    }
  },
  // Client and usage tracking
  usageHistory: [{
    clientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    usedAt: {
      type: Date,
      default: Date.now
    },
    originalAmount: {
      type: Number,
      required: true
    },
    discountAmount: {
      type: Number,
      required: true
    },
    finalAmount: {
      type: Number,
      required: true
    },
    serviceType: String,
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Booking'
    }
  }],
  // Marketing and analytics
  marketing: {
    campaign: {
      type: String,
      trim: true,
      maxlength: [100, 'Campaign name cannot exceed 100 characters']
    },
    source: {
      type: String,
      enum: ['website', 'email', 'social_media', 'referral', 'admin'],
      default: 'admin'
    },
    isPromoted: {
      type: Boolean,
      default: false
    }
  },
  // Analytics
  analytics: {
    totalViews: {
      type: Number,
      default: 0,
      min: 0
    },
    conversionRate: {
      type: Number,
      default: 0,
      min: 0,
      max: 100
    },
    totalRevenue: {
      type: Number,
      default: 0,
      min: 0
    },
    totalSavings: {
      type: Number,
      default: 0,
      min: 0
    }
  },
  // Auto-generation settings
  autoGenerated: {
    type: Boolean,
    default: false
  },
  generationRules: {
    prefix: String,
    length: {
      type: Number,
      min: 3,
      max: 20
    },
    includeNumbers: {
      type: Boolean,
      default: true
    }
  },
  // Stacking and combination rules
  stackable: {
    type: Boolean,
    default: false
  },
  excludedCoupons: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Coupon'
  }],
  // Notification settings
  notifications: {
    notifyOnUse: {
      type: Boolean,
      default: true
    },
    notifyOnExpiry: {
      type: Boolean,
      default: true
    },
    expiryWarningDays: {
      type: Number,
      default: 7,
      min: 1,
      max: 30
    }
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes for efficient queries
couponSchema.index({ code: 1 }, { unique: true });
couponSchema.index({ therapistId: 1, isActive: 1 });
couponSchema.index({ validFrom: 1, validUntil: 1 });
couponSchema.index({ isActive: 1, validFrom: 1, validUntil: 1 });
couponSchema.index({ couponType: 1, targetAudience: 1 });

// Virtual for therapist details
couponSchema.virtual('therapist', {
  ref: 'User',
  localField: 'therapistId',
  foreignField: '_id',
  justOne: true
});

// Virtual for remaining uses
couponSchema.virtual('remainingUses').get(function() {
  if (!this.maxUses) return null; // Unlimited uses
  return Math.max(0, this.maxUses - this.usedCount);
});

// Virtual for is expired
couponSchema.virtual('isExpired').get(function() {
  return new Date() > this.validUntil;
});

// Virtual for is valid now
couponSchema.virtual('isValidNow').get(function() {
  const now = new Date();
  return this.isActive &&
         now >= this.validFrom &&
         now <= this.validUntil &&
         (this.maxUses === null || this.usedCount < this.maxUses);
});

// Virtual for days until expiry
couponSchema.virtual('daysUntilExpiry').get(function() {
  const now = new Date();
  const diffTime = this.validUntil - now;
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
});

// Virtual for usage percentage
couponSchema.virtual('usagePercentage').get(function() {
  if (!this.maxUses) return 0;
  return Math.round((this.usedCount / this.maxUses) * 100);
});

// Method to validate coupon for specific use
couponSchema.methods.validateForUse = function(clientId, amount, serviceType) {
  const now = new Date();

  // Check if coupon is active
  if (!this.isActive) {
    return { valid: false, reason: 'Coupon is not active' };
  }

  // Check validity period
  if (now < this.validFrom || now > this.validUntil) {
    return { valid: false, reason: 'Coupon is not valid at this time' };
  }

  // Check usage limits
  if (this.maxUses && this.usedCount >= this.maxUses) {
    return { valid: false, reason: 'Coupon has reached maximum usage limit' };
  }

  // Check minimum amount
  if (amount < this.minAmount) {
    return { valid: false, reason: `Minimum amount of ${this.minAmount} required` };
  }

  // Check applicable services
  if (!this.applicableServices.includes('all') && !this.applicableServices.includes(serviceType)) {
    return { valid: false, reason: 'Coupon not applicable for this service type' };
  }

  // Check one-time per client restriction
  if (this.restrictions.oneTimePerClient) {
    const hasUsed = this.usageHistory.some(usage =>
      usage.clientId.toString() === clientId.toString()
    );
    if (hasUsed) {
      return { valid: false, reason: 'Coupon already used by this client' };
    }
  }

  return { valid: true };
};

// Method to calculate discount
couponSchema.methods.calculateDiscount = function(amount) {
  if (this.discountType === 'percentage') {
    return Math.round((amount * this.discountValue / 100) * 100) / 100;
  } else {
    return Math.min(this.discountValue, amount);
  }
};

// Method to apply coupon
couponSchema.methods.applyCoupon = function(clientId, originalAmount, serviceType, bookingId = null) {
  const validation = this.validateForUse(clientId, originalAmount, serviceType);

  if (!validation.valid) {
    throw new Error(validation.reason);
  }

  const discountAmount = this.calculateDiscount(originalAmount);
  const finalAmount = originalAmount - discountAmount;

  // Record usage
  this.usageHistory.push({
    clientId,
    originalAmount,
    discountAmount,
    finalAmount,
    serviceType,
    bookingId
  });

  this.usedCount += 1;

  // Update analytics
  this.analytics.totalRevenue += finalAmount;
  this.analytics.totalSavings += discountAmount;

  return this.save().then(() => ({
    originalAmount,
    discountAmount,
    finalAmount,
    discountPercentage: Math.round((discountAmount / originalAmount) * 100)
  }));
};

// Method to deactivate coupon
couponSchema.methods.deactivate = function() {
  this.isActive = false;
  return this.save();
};

// Method to extend validity
couponSchema.methods.extendValidity = function(newValidUntil) {
  if (newValidUntil <= this.validUntil) {
    throw new Error('New validity date must be after current validity date');
  }
  this.validUntil = newValidUntil;
  return this.save();
};

// Method to increase usage limit
couponSchema.methods.increaseUsageLimit = function(additionalUses) {
  if (this.maxUses === null) {
    this.maxUses = additionalUses;
  } else {
    this.maxUses += additionalUses;
  }
  return this.save();
};

// Static method to generate unique coupon code
couponSchema.statics.generateUniqueCode = async function(prefix = '', length = 8) {
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let attempts = 0;
  const maxAttempts = 100;

  while (attempts < maxAttempts) {
    let code = prefix;
    const remainingLength = length - prefix.length;

    for (let i = 0; i < remainingLength; i++) {
      code += characters.charAt(Math.floor(Math.random() * characters.length));
    }

    const existing = await this.findOne({ code });
    if (!existing) {
      return code;
    }

    attempts++;
  }

  throw new Error('Unable to generate unique coupon code after maximum attempts');
};

// Static method to get active coupons for therapist
couponSchema.statics.getActiveCoupons = function(therapistId) {
  const now = new Date();
  return this.find({
    therapistId,
    isActive: true,
    validFrom: { $lte: now },
    validUntil: { $gte: now },
    $or: [
      { maxUses: null },
      { $expr: { $lt: ['$usedCount', '$maxUses'] } }
    ]
  }).sort({ validUntil: 1 });
};

// Static method to get expiring coupons
couponSchema.statics.getExpiringCoupons = function(daysAhead = 7) {
  const now = new Date();
  const futureDate = new Date(now.getTime() + (daysAhead * 24 * 60 * 60 * 1000));

  return this.find({
    isActive: true,
    validUntil: { $gte: now, $lte: futureDate }
  }).populate('therapist', 'name email');
};

// Static method to get coupon statistics
couponSchema.statics.getCouponStats = function(therapistId = null) {
  const matchQuery = therapistId ? { therapistId: new mongoose.Types.ObjectId(therapistId) } : {};

  return this.aggregate([
    { $match: matchQuery },
    {
      $group: {
        _id: '$couponType',
        count: { $sum: 1 },
        totalUsed: { $sum: '$usedCount' },
        totalRevenue: { $sum: '$analytics.totalRevenue' },
        totalSavings: { $sum: '$analytics.totalSavings' },
        avgConversion: { $avg: '$analytics.conversionRate' }
      }
    },
    { $sort: { count: -1 } }
  ]);
};

// Pre-save middleware
couponSchema.pre('save', function(next) {
  // Ensure code is uppercase
  if (this.isModified('code')) {
    this.code = this.code.toUpperCase();
  }

  // Calculate conversion rate
  if (this.analytics.totalViews > 0) {
    this.analytics.conversionRate = Math.round((this.usedCount / this.analytics.totalViews) * 100 * 10) / 10;
  }

  next();
});

// Pre-validate middleware
couponSchema.pre('validate', function(next) {
  // Validate time restrictions format
  if (this.restrictions.timeRestrictions.startTime) {
    const timeRegex = /^([01]?[0-9]|2[0-3]):[0-5][0-9]$/;
    if (!timeRegex.test(this.restrictions.timeRestrictions.startTime)) {
      return next(new Error('Invalid start time format. Use HH:MM format.'));
    }
  }

  if (this.restrictions.timeRestrictions.endTime) {
    const timeRegex = /^([01]?[0-9]|2[0-3]):[0-5][0-9]$/;
    if (!timeRegex.test(this.restrictions.timeRestrictions.endTime)) {
      return next(new Error('Invalid end time format. Use HH:MM format.'));
    }
  }

  next();
});

// Post-save middleware
couponSchema.post('save', function() {
  // Here you would trigger notifications or analytics updates
  // Example: notificationService.notifyCouponUpdate(this);
});

module.exports = mongoose.model('Coupon', couponSchema);